<?php

namespace app\back\controller;

use app\common\model\Anli;
use app\common\model\Shipin;
use think\Db;
use think\Request;
use app\common\model\CateShipin;

class CateShipinController extends BaseController {
    public function __construct() {
        parent::__construct(); // TODO: Change the autogenerated stub
        $this->assign(['modelName'=>'视频分类']);

    }

    public function index(Request $request) {

        $data = $request->param();
        $list_ = CateShipin::getList($data);
        $url = $request->url();
        return $this->fetch('',['list_'=>$list_,'url'=>$url]);
    }

    public function create() {

            return $this->fetch('', ['act'=>'save']);
    }

    public function save(Request $request) {
        $data = $request->param();
        $res = $this->validate($data,'CateValidate');
        if($res!==true){
            $this->error($res);
        }
        if((new CateShipin())->save($data)){
            $this->success('添加成功','index','',1);
        }else{
            $this->error('添加出错');
        }

    }

    public function edit(Request $request) {
        $data = $request->param();
        $referer= $request->header()['referer'];
        //dump($referer);
        $row_ = $this->findById($data['id'],new CateShipin());
        return $this->fetch('create',['row_'=>$row_,'referer'=>$referer,'act'=>'update']);

    }

    public function update(Request $request) {
        //return 233;
        $data = $request->param();
        $referer = $data['referer'];unset($data['referer']);
        $res = $this->validate($data,'CateValidate');
        if($res!==true){
            $this->error($res);
        }
        if($this->saveById($data['id'],new CateShipin(),$data)){
            $this->success('修改成功', $referer, '', 1);
        }else{
            $this->error('没有修改内容', $referer);
        }
    }

    public function delete(Request $request) {
        $data = $request->param();
         $list_good = Shipin::getListByCateId($data['id']);
        if(count($list_good)>0){
            $this->error('分类下有视频，不能直接删除');
        }
        if ($this->deleteStatusById($data['id'], new CateShipin())) {
            $this->success('删除成功', $data['url'], '', 1);
        } else {
            $this->error('删除失败', $data['url']);
        }
    }
}
